version: '3.1'
services:
  draco:
    image: ging/fiware-draco:2.1.0
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    ports:
      - "9090:9090"
      - "5050:5050"
  # db-mysql:
  #   image: mysql:5.7.22
  #   container_name: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #     environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     ports:
  #     - "3306:3306"
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  # mongo-db:
  #   image: mongo:3.4
  #   restart: always
  #     ports:
  #     - "27017:27017"
  # db-cassandra:
  #   image: cassandra
  #   restart: always
  #      ports:
  #     - "9042:9042"
